# Generated by Django 4.2.8 on 2024-02-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urunler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=50, verbose_name='Ürün Adı')),
                ('fiyat', models.IntegerField(blank=True, verbose_name='Ürün Fiyatı')),
                ('urun_resmi', models.ImageField(max_length=1000, upload_to='urun', verbose_name='Ürün Resmi')),
                ('aciklama', models.TextField(verbose_name='Ürün Aciklaması')),
            ],
        ),
    ]
