# Generated by Django 4.2.8 on 2024-02-17 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppMy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=50, verbose_name='Kategori Adı')),
            ],
        ),
        migrations.AddField(
            model_name='urunler',
            name='kategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppMy.kategori'),
        ),
    ]
