# Generated by Django 4.2.8 on 2024-02-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMy', '0002_kategori_urunler_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategori',
            name='slug',
            field=models.CharField(default='djangodbmodelsfieldscharfield', max_length=50, verbose_name='Slug'),
        ),
    ]
