# Generated by Django 4.2.8 on 2024-02-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMy', '0003_kategori_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategori',
            name='adi',
            field=models.SlugField(verbose_name='Kategori Adı'),
        ),
        migrations.AlterField(
            model_name='kategori',
            name='slug',
            field=models.SlugField(null=True, verbose_name='Slug'),
        ),
    ]
