# Generated by Django 4.2.8 on 2024-02-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMy', '0004_alter_kategori_adi_alter_kategori_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategori',
            name='adi',
            field=models.CharField(max_length=50, verbose_name='Kategori Adı'),
        ),
    ]
