# Generated by Django 4.2.8 on 2024-02-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMy', '0005_alter_kategori_adi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iletisim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50, verbose_name='Ad')),
                ('soyad', models.CharField(max_length=50, verbose_name='Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('mesaj', models.TextField(verbose_name='Mesaj')),
                ('telefon', models.CharField(max_length=50, verbose_name='Telefon')),
            ],
        ),
    ]
