# Generated by Django 4.2.8 on 2024-02-17 20:49

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('AppMy', '0006_iletisim'),
    ]

    operations = [
        migrations.AddField(
            model_name='urunler',
            name='slug',
            field=models.SlugField(null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='iletisim',
            name='telefon',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Telefon'),
        ),
    ]
