# Generated by Django 4.2.8 on 2024-02-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMy', '0007_urunler_slug_alter_iletisim_telefon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yorumlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=50, verbose_name='Ad Soyad')),
                ('mesaj', models.TextField(verbose_name='Mesaj')),
                ('tarih', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
            ],
        ),
    ]
