# Generated by Django 4.2.8 on 2024-02-18 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppMy', '0008_yorumlar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yorumlar',
            name='mesaj',
        ),
        migrations.AddField(
            model_name='yorumlar',
            name='urun',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppMy.urunler'),
        ),
        migrations.AddField(
            model_name='yorumlar',
            name='yorum',
            field=models.TextField(null=True, verbose_name='yorum'),
        ),
        migrations.AlterField(
            model_name='yorumlar',
            name='tarih',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Tarih'),
        ),
    ]
